# /docker-compose.yml

services:
  news:
    build: .
    env_file:
      - .env
    ports:
      - "0.0.0.0:8003:8000"  # Слушаем на всех интерфейсах
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3