# /docker-compose.yml

version: '3.8'

services:
  news:
    build: .
    env_file:
      - .env
    ports:
      - "127.0.0.1:8003:8000"  # Слушаем только localhost
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3